const fs = require('fs');
const path = require('path');

const dataFilePath = path.join(__dirname, 'js', 'data.js');
let dataContent = fs.readFileSync(dataFilePath, 'utf8');

const basePlacesRegex = /const\s+BASE_PLACES\s*=\s*\[([\s\S]*?)\];/;

const newBasePlacesStr = `const BASE_PLACES = [
  // ── NHÀ HÀNG & QUÁN ĂN ──────────────────────────────────────────
  {
    id: 1,
    name: 'Nhà hàng Royal Tuyên Quang',
    slug: 'royal-tuyen-quang',
    category: 'an-uong',
    subCategory: 'Nhà hàng',
    description: 'Địa điểm sang trọng, không gian hiện đại, chuyên đặc sản địa phương và hải sản tươi sống.',
    fullDescription: 'Royal Tuyên Quang là một trong những nhà hàng sang trọng bậc nhất thành phố trong năm 2026. Với thiết kế hiện đại, không gian mở thoáng đãng và hệ thống phòng VIP đẳng cấp, đây là lựa chọn hàng đầu cho các buổi tiệc gia đình, tiếp khách hoặc sự kiện lớn. Thực đơn giao thoa giữa đặc sản địa phương vùng núi và hải sản tươi sống nhập trong ngày.',
    address: '08 Mạc Đĩnh Chi, Phường Tân Quang, TP. Tuyên Quang',
    phone: '0207 381 8888',
    priceRange: '$$$',
    priceText: '200.000đ - 600.000đ',
    rating: 4.8,
    totalReviews: 845,
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80'],
    imageColors: ['#8E44AD', '#9B59B6', '#F4A261'],
    openHours: 'T2-CN: 10:00 - 22:30',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['sang trọng', 'hải sản', 'tiệc cưới', 'phòng VIP'],
    amenities: ['Bãi đỗ xe', 'Phòng VIP', 'Điều hòa', 'Thanh toán thẻ'],
    coordinates: { lat: 21.8210, lng: 105.2150 },
    social: { facebook: 'https://facebook.com/royal.tuyenquang', zalo: '02073818888', instagram: '' },
    menu: [
      { name: 'Cá hồi Sapa ăn sống', price: '350.000đ' },
      { name: 'Lẩu cá lăng chua cay', price: '450.000đ' },
      { name: 'Gà đồi nướng mắc khén', price: '280.000đ' },
      { name: 'Ba ba rang muối', price: '600.000đ' }
    ],
    reviews: []
  },
  {
    id: 2,
    name: 'Nhà hàng Ẩm Thực Việt',
    slug: 'am-thuc-viet-tq',
    category: 'an-uong',
    subCategory: 'Nhà hàng',
    description: 'Quy mô lớn với thực đơn hơn 100 món Á Đông, không gian cực kỳ rộng rãi và thoáng mát.',
    fullDescription: 'Tọa lạc trên đường Phan Bội Châu, Ẩm Thực Việt tự hào sở hữu thực đơn hơn 100 món ăn từ truyền thống Việt Nam đến phong cách Á Đông đương đại. Quán nổi tiếng với nguồn nguyên liệu tươi ngon, đặc biệt là các món chế biến từ cá sông Lô và lợn bản đen.',
    address: 'Đường Phan Bội Châu, Phường Phan Thiết, TP. Tuyên Quang',
    phone: '0988 123 456',
    priceRange: '$$',
    priceText: '150.000đ - 350.000đ',
    rating: 4.6,
    totalReviews: 620,
    images: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80'],
    imageColors: ['#E76F51', '#F4A261', '#E9C46A'],
    openHours: 'T2-CN: 09:00 - 22:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['gia đình', 'đa dạng', 'cá sông Lô', 'nhậu'],
    amenities: ['Sân vườn', 'Bãi đỗ xe rộng', 'Máy lạnh'],
    coordinates: { lat: 21.8280, lng: 105.2120 },
    social: { facebook: 'https://facebook.com/amthucviet.tq', zalo: '0988123456', instagram: '' },
    menu: [
      { name: 'Cá bỗng sông Lô nướng', price: '250.000đ' },
      { name: 'Lợn đen quay giòn da', price: '180.000đ' },
      { name: 'Nộm hoa chuối tai heo', price: '80.000đ' },
      { name: 'Lẩu riêu cua bắp bò', price: '300.000đ' }
    ],
    reviews: []
  },
  {
    id: 3,
    name: 'MỘC Restaurant',
    slug: 'moc-restaurant-tq',
    category: 'an-uong',
    subCategory: 'Quán ăn',
    description: 'Chuyên đặc sản dê núi, gà đồi với không gian mộc mạc, gần gũi thiên nhiên.',
    fullDescription: 'Đúng như tên gọi, MỘC mang đến không gian dùng bữa ấm cúng, bài trí chủ đạo bằng gỗ và cây xanh. Nhà hàng liên tục cập nhật menu theo mùa, nổi tiếng nhất với đặc sản dê núi đá và gà đồi chạy bộ thịt chắc, ngọt.',
    address: '124 Trần Hưng Đạo, Phường Minh Xuân, TP. Tuyên Quang',
    phone: '0355 999 888',
    priceRange: '$$',
    priceText: '100.000đ - 250.000đ',
    rating: 4.7,
    totalReviews: 412,
    images: ['https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&q=80'],
    imageColors: ['#5A7D59', '#3E5C3D', '#C5A059'],
    openHours: 'T2-CN: 10:00 - 23:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['dê núi', 'gà đồi', 'mộc mạc', 'nhậu'],
    amenities: ['Chỗ ngồi ngoài trời', 'WiFi', 'Chỗ để xe máy'],
    coordinates: { lat: 21.8250, lng: 105.2180 },
    social: { facebook: 'https://facebook.com/moc.restaurant.tq', zalo: '0355999888', instagram: '' },
    menu: [
      { name: 'Dê xào lăn', price: '150.000đ' },
      { name: 'Dê tái chanh', price: '140.000đ' },
      { name: 'Gà đồi rang muối', price: '160.000đ' },
      { name: 'Lẩu dê nhúng mẻ', price: '250.000đ' }
    ],
    reviews: []
  },
  {
    id: 4,
    name: 'Nhà hàng Dũng Cá',
    slug: 'nha-hang-dung-ca',
    category: 'an-uong',
    subCategory: 'Nhà hàng',
    description: 'Biểu tượng ẩm thực ven sông Lô, chuyên trị các món cá sông tươi rói bắt ngay tại lồng.',
    fullDescription: 'Nhà hàng Dũng Cá có vị trí đắc địa nhìn thẳng ra sông Lô thơ mộng. Đặc trưng của quán là hệ thống lồng cá nuôi trực tiếp dưới sông, khách đến chỉ việc chọn cá đang bơi và bếp sẽ chế biến ngay lập tức. Cực kỳ nổi tiếng với Gỏi cá bỗng.',
    address: 'Đường ven sông Lô (đối diện siêu thị Tuyên Quang)',
    phone: '0912 345 789',
    priceRange: '$$$',
    priceText: '250.000đ - 500.000đ',
    rating: 4.8,
    totalReviews: 1250,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&q=80'],
    imageColors: ['#2B4B6F', '#1A2F45', '#E9C46A'],
    openHours: 'T2-CN: 09:00 - 22:30',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['cá sông', 'view sông Lô', 'đặc sản', 'gỏi cá'],
    amenities: ['View sông', 'Phòng riêng', 'Bãi đỗ xe'],
    coordinates: { lat: 21.8225, lng: 105.2100 },
    social: { facebook: 'https://facebook.com/dungca.tq', zalo: '0912345789', instagram: '' },
    menu: [
      { name: 'Gỏi cá bỗng sông Lô', price: '280.000đ' },
      { name: 'Cá lăng nướng than hoa', price: '300.000đ' },
      { name: 'Lẩu cá tầm', price: '450.000đ' },
      { name: 'Cá chình nướng riềng mẻ', price: '350.000đ' }
    ],
    reviews: []
  },
  {
    id: 5,
    name: 'Min-Max BBQ',
    slug: 'min-max-bbq',
    category: 'an-uong',
    subCategory: 'Nhà hàng',
    description: 'Thiên đường lẩu nướng không khói phong cách Hàn Quốc, giá cả cực kỳ hợp lý cho giới trẻ.',
    fullDescription: 'Min-Max BBQ là điểm tụ tập quen thuộc của giới trẻ và các gia đình trẻ tại Tuyên Quang. Quán trang bị hệ thống hút mùi âm bàn hiện đại, phục vụ buffet nướng và lẩu với hàng chục loại thịt bò Mỹ, hải sản và panchan chuẩn vị Hàn.',
    address: 'Khu đô thị Việt Mỹ, Phường Phan Thiết, TP. Tuyên Quang',
    phone: '0987 654 321',
    priceRange: '$$',
    priceText: '169.000đ - 250.000đ/Buffet',
    rating: 4.5,
    totalReviews: 890,
    images: ['https://images.unsplash.com/photo-1544148103-0773bf10d330?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80'],
    imageColors: ['#E76F51', '#F4A261', '#264653'],
    openHours: 'T2-CN: 17:00 - 23:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['buffet', 'lẩu nướng', 'bbq', 'hàn quốc', 'giới trẻ'],
    amenities: ['Điều hòa', 'Hút mùi', 'Buffet'],
    coordinates: { lat: 21.8260, lng: 105.2165 },
    social: { facebook: 'https://facebook.com/minmaxbbq.tq', zalo: '0987654321', instagram: '' },
    menu: [
      { name: 'Buffet nướng tiêu chuẩn', price: '169.000đ' },
      { name: 'Buffet lẩu nướng tổng hợp', price: '219.000đ' },
      { name: 'Buffet VIP Hải Sản', price: '289.000đ' }
    ],
    reviews: []
  },

  // ── CAFE & TRÀ SỮA ──────────────────────────────────────────
  {
    id: 6,
    name: 'Koi and You Coffee',
    slug: 'koi-and-you-coffee',
    category: 'an-uong',
    subCategory: 'Cafe & Trà sữa',
    description: 'Cafe cá Koi lãng mạn, hồ cá tuyệt đẹp nằm giữa khuôn viên, điểm sống ảo hot nhất Tuyên Quang.',
    fullDescription: 'Koi and You mang đến một không gian xanh mát, thư giãn tuyệt đối với hồ cá Koi Nhật Bản trị giá hàng tỷ đồng ngay giữa trung tâm quán. Thiết kế mở, kết hợp cầu gỗ và tiểu cảnh bonsai khiến nơi đây trở thành góc check-in không thể bỏ lỡ của năm 2026.',
    address: 'Khu đô thị Việt Mỹ Villas, đường Lê Lợi 4, tổ 12, Phường Phan Thiết',
    phone: '0901 234 567',
    priceRange: '$$',
    priceText: '35.000đ - 70.000đ',
    rating: 4.8,
    totalReviews: 1050,
    images: ['https://images.unsplash.com/photo-1541123437800-1bb1317bc920?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&q=80'],
    imageColors: ['#E76F51', '#2A9D8F', '#264653'],
    openHours: 'T2-CN: 07:00 - 22:30',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['cá koi', 'sống ảo', 'ngoài trời', 'thư giãn'],
    amenities: ['Hồ cá Koi', 'Bãi đỗ xe ô tô', 'Máy lạnh', 'Thức ăn cá'],
    coordinates: { lat: 21.8255, lng: 105.2175 },
    social: { facebook: 'https://facebook.com/koiandyou.tq', zalo: '0901234567', instagram: '' },
    menu: [
      { name: 'Cà phê muối', price: '45.000đ' },
      { name: 'Trà sen vàng', price: '50.000đ' },
      { name: 'Nước ép mix nhiệt đới', price: '55.000đ' },
      { name: 'Mồi cho cá Koi', price: '10.000đ' }
    ],
    reviews: []
  },
  {
    id: 7,
    name: 'Laika Cafe',
    slug: 'laika-cafe-tq',
    category: 'an-uong',
    subCategory: 'Cafe & Trà sữa',
    description: 'Phong cách cổ điển pha hiện đại, tone màu vàng trắng sang chảnh chuẩn Gu thủ đô.',
    fullDescription: 'Thương hiệu Laika đình đám đã có mặt tại Tuyên Quang. Quán nổi bật với thiết kế tone vàng - trắng bắt mắt, ban công tầng 2 rộng rãi và hệ thống ánh sáng được setup chuẩn studio, đảm bảo cứ giơ máy lên là có ảnh đẹp.',
    address: '102 Quang Trung, Phường Tân Quang',
    phone: '0345 678 910',
    priceRange: '$$',
    priceText: '40.000đ - 65.000đ',
    rating: 4.6,
    totalReviews: 890,
    images: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80'],
    imageColors: ['#E9C46A', '#F4A261', '#FFFFFF'],
    openHours: 'T2-CN: 08:00 - 23:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['sang chảnh', 'ban công', 'chuỗi', 'check-in'],
    amenities: ['Ban công', 'Điều hòa 24/7', 'Wifi mạnh', 'Chụp ảnh cưới'],
    coordinates: { lat: 21.8215, lng: 105.2185 },
    social: { facebook: 'https://facebook.com/laikacafe.tq', zalo: '0345678910', instagram: '' },
    menu: [
      { name: 'Trà nhài đác thơm', price: '55.000đ' },
      { name: 'Cà phê cốt dừa', price: '50.000đ' },
      { name: 'Bạc xỉu đá', price: '45.000đ' },
      { name: 'Bánh sừng bò (Croissant)', price: '40.000đ' }
    ],
    reviews: []
  },
  {
    id: 8,
    name: 'Cielo Coffee & Ice Cream',
    slug: 'cielo-coffee',
    category: 'an-uong',
    subCategory: 'Cafe & Trà sữa',
    description: 'Không gian hiện đại, rộng rãi, tụ tập bạn bè và thưởng thức kem Ý Gelato đỉnh cao.',
    fullDescription: 'Cielo mang phong cách công nghiệp hiện đại (Industrial) với trần cao và tường kính đón nắng tự nhiên. Quán không chỉ nổi tiếng với đồ uống chất lượng mà còn là địa chỉ bán kem Ý Gelato làm thủ công ngon nhất thành phố Tuyên Quang.',
    address: '51 Bình Thuận, TP. Tuyên Quang',
    phone: '0977 888 999',
    priceRange: '$$',
    priceText: '30.000đ - 80.000đ',
    rating: 4.7,
    totalReviews: 650,
    images: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1488597728638-76901802e3b2?auto=format&fit=crop&q=80'],
    imageColors: ['#264653', '#2A9D8F', '#F4A261'],
    openHours: 'T2-CN: 08:30 - 22:30',
    isOpen: true,
    isFeatured: false,
    isNew: true,
    tags: ['kem ý', 'gelato', 'hiện đại', 'trần cao'],
    amenities: ['Tủ kem tươi', 'Khu hút thuốc riêng', 'Wifi'],
    coordinates: { lat: 21.8230, lng: 105.2140 },
    social: { facebook: 'https://facebook.com/cielocoffee.tq', zalo: '0977888999', instagram: '' },
    menu: [
      { name: 'Kem Gelato Bỉ (1 viên)', price: '35.000đ' },
      { name: 'Trà xoài macchiato', price: '50.000đ' },
      { name: 'Cà phê ủ lạnh (Cold Brew)', price: '55.000đ' }
    ],
    reviews: []
  },
  {
    id: 9,
    name: 'Feline Café',
    slug: 'feline-cafe',
    category: 'an-uong',
    subCategory: 'Cafe & Trà sữa',
    description: 'Quán cafe theo mùa, decor liên tục thay đổi theo concept Lễ, Tết, Giáng Sinh.',
    fullDescription: 'Nếu bạn là người đam mê đổi ảnh đại diện thường xuyên, Feline Café là chân ái. Mỗi tháng quán lại biến hóa không gian theo một chủ đề khác nhau: concept Trung Thu, concept Giáng Sinh lấp lánh, hay concept Tết cổ truyền. Đồ uống đi kèm bánh ngọt rất bắt mắt.',
    address: '126 Bình Thuận, TP. Tuyên Quang',
    phone: '0888 111 222',
    priceRange: '$$',
    priceText: '35.000đ - 65.000đ',
    rating: 4.5,
    totalReviews: 780,
    images: ['https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80'],
    imageColors: ['#E9C46A', '#FFB5C2', '#B5EAD7'],
    openHours: 'T2-CN: 08:00 - 22:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['concept', 'chụp ảnh', 'bánh ngọt', 'đổi mới'],
    amenities: ['Phụ kiện chụp ảnh', 'Gương soi', 'Điều hòa'],
    coordinates: { lat: 21.8235, lng: 105.2145 },
    social: { facebook: 'https://facebook.com/felinecafe.tq', zalo: '0888111222', instagram: '' },
    menu: [
      { name: 'Trà cam quế', price: '45.000đ' },
      { name: 'Bánh Red Velvet', price: '40.000đ' },
      { name: 'Trà sữa olong nướng', price: '45.000đ' }
    ],
    reviews: []
  },

  // ── VUI CHƠI & MUA SẮM ──────────────────────────────────────────
  {
    id: 10,
    name: 'Rạp chiếu phim Lotte Cinema Tuyên Quang',
    slug: 'lotte-cinema-tq',
    category: 'vui-choi',
    subCategory: 'Rạp phim',
    description: 'Cụm rạp tiêu chuẩn quốc tế với hệ thống âm thanh vòm đỉnh cao.',
    fullDescription: 'Nằm trong TTTM lớn nhất thành phố, Lotte Cinema mang đến trải nghiệm điện ảnh chuẩn Hàn Quốc với ghế ngồi rộng rãi, độ dốc hợp lý, màn hình cong siêu nét và combo bắp nước đa dạng.',
    address: 'Tầng 3, TTTM Vincom Tuyên Quang',
    phone: '1900 1234',
    priceRange: '$$',
    priceText: '55.000đ - 110.000đ/vé',
    rating: 4.7,
    totalReviews: 1450,
    images: ['https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&q=80'],
    imageColors: ['#E76F51', '#2B4B6F', '#1A2F45'],
    openHours: 'T2-CN: 08:30 - 23:30',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['phim', 'bom tấn', 'vincom', 'giải trí'],
    amenities: ['Ghế đôi', 'Bãi đỗ xe hầm', 'Máy lạnh'],
    coordinates: { lat: 21.8242, lng: 105.2168 },
    social: { facebook: 'https://facebook.com/lottecinematuyenquang', zalo: '', instagram: '' },
    menu: [],
    reviews: []
  },
  {
    id: 11,
    name: 'Tiệm Đồ Boho - Boho Chic',
    slug: 'boho-chic-tq',
    category: 'trang-phuc',
    subCategory: 'Quần áo',
    description: 'Chuyên cho thuê trang phục phong cách Bohemian chụp ảnh ngoại cảnh.',
    fullDescription: 'Cửa hàng cung cấp hàng trăm mẫu váy Maxi, đầm Boho, phụ kiện thổ cẩm cực chất để phục vụ du khách đi check-in tại Bản Khun, Na Hang hay các cánh đồng hoa. Giá thuê rẻ, đồ luôn được giặt thơm tho sạch sẽ.',
    address: '15 Lê Lợi, TP. Tuyên Quang',
    phone: '0909 888 777',
    priceRange: '$',
    priceText: '80.000đ - 150.000đ/ngày',
    rating: 4.8,
    totalReviews: 210,
    images: ['https://images.unsplash.com/photo-1485230405346-71acb9518d9c?auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1515347619152-16e788eb5cc3?auto=format&fit=crop&q=80'],
    imageColors: ['#C5A059', '#D4A373', '#9B59B6'],
    openHours: 'T2-CN: 08:00 - 21:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['boho', 'thuê đồ', 'chụp ảnh', 'du lịch'],
    amenities: ['Thử đồ', 'Phụ kiện đi kèm', 'Giặt sấy'],
    coordinates: { lat: 21.8220, lng: 105.2140 },
    social: { facebook: 'https://facebook.com/bohochic.tq', zalo: '0909888777', instagram: '' },
    menu: [],
    reviews: []
  }
];`;

dataContent = dataContent.replace(basePlacesRegex, newBasePlacesStr);
fs.writeFileSync(dataFilePath, dataContent, 'utf8');
console.log('Update complete.');
