// Tourism data for Tuyên Quang
// Each item needs all required fields to work with detail pages

export const TOURISM_PLACES = [
  {
    id: 302,
    name: 'Khu Di Tích Lịch Sử ATK Tân Trào',
    slug: 'atk-tan-trao',
    category: 'du-lich',
    subCategory: 'Di tích lịch sử',
    rating: 4.9,
    totalReviews: 2450,
    image: 'https://images.unsplash.com/photo-1542361345-89e58247f2d5?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1542361345-89e58247f2d5?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1601618332147-380145df0e59?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#7C9082', '#4A5B4D'],
    address: 'Xã Tân Trào, huyện Sơn Dương, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 21.68, lng: 105.32 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'T2-CN: 07:00 - 17:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    description: 'Thủ đô Khu Giải phóng - Căn cứ địa cách mạng hào hùng. Phiên bản 2026 đã kiện toàn Bảo tàng ATK Tân Trào hiện đại, kết hợp tham quan Lán Nà Nưa, Cây đa Tân Trào và Đình Hồng Thái với nhiều ứng dụng công nghệ thực tế ảo.',
    tags: ['Lịch sử', 'Văn hóa', 'Bảo tàng', 'Tâm linh'],
    amenities: ['Bãi đỗ xe rộng', 'Thuyết minh viên', 'Bảo tàng số', 'Khu mua sắm'],
    social: {},
    reviews: []
  },
  {
    id: 303,
    name: 'Khu Du Lịch Sinh Thái Na Hang - Lâm Bình',
    slug: 'na-hang-lam-binh',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    rating: 5.0,
    totalReviews: 3200,
    image: 'https://images.unsplash.com/photo-1506461883276-594c8cb257a1?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1506461883276-594c8cb257a1?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#2B4B6F', '#1A2F45'],
    address: 'Huyện Na Hang và Lâm Bình, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 22.35, lng: 105.39 },
    priceRange: '500.000đ - 2.500.000đ',
    priceText: '500.000đ - 2.500.000đ',
    openHours: 'T2-CN: 06:00 - 22:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    description: 'Được mệnh danh là "Hạ Long giữa đại ngàn". Khu du lịch nổi bật với các hoạt động mới như chèo kayak trên hồ thủy điện, trekking khám phá hang động hoang sơ, cắm trại qua đêm và chiêm ngưỡng danh thắng Cọc Vài Phạ hùng vĩ.',
    tags: ['Khám phá', 'Cảnh quan', 'Cắm trại', 'Chèo Kayak'],
    amenities: ['Tàu du lịch', 'Homestay', 'Cho thuê Kayak', 'Nhà hàng nổi'],
    social: {},
    reviews: []
  },
  {
    id: 304,
    name: 'Suối Khoáng Nóng Mỹ Lâm',
    slug: 'suoi-khoang-my-lam',
    category: 'du-lich',
    subCategory: 'Suối & Thác',
    rating: 4.7,
    totalReviews: 1540,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1621293954908-907159247fc8?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#8A9A5B', '#556B2F'],
    address: 'Phường Mỹ Lâm, TP. Tuyên Quang',
    phone: '',
    coordinates: { lat: 21.75, lng: 105.18 },
    priceRange: '150.000đ - 1.000.000đ',
    priceText: '150.000đ - 1.000.000đ',
    openHours: 'T2-CN: 08:00 - 21:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    description: 'Khu du lịch nghỉ dưỡng cao cấp với nguồn nước khoáng nóng tự nhiên dưới lòng đất (68 độ C), giàu khoáng chất cực kỳ tốt cho sức khỏe. Tại đây có các dịch vụ tắm bùn khoáng, tắm sục, spa trị liệu chuẩn quốc tế.',
    tags: ['Nghỉ dưỡng', 'Trị liệu', 'Gia đình', 'Spa'],
    amenities: ['Resort', 'Tắm bùn', 'Hồ bơi khoáng nóng', 'Nhà hàng'],
    social: {},
    reviews: []
  },
  {
    id: 305,
    name: 'Ruộng Bậc Thang Hồng Thái',
    slug: 'ruong-bac-thang-hong-thai',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    rating: 4.9,
    totalReviews: 890,
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#C5A059', '#8C6C3A'],
    address: 'Xã Hồng Thái, huyện Na Hang, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 22.45, lng: 105.45 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'T2-CN: 06:00 - 18:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    description: 'Điểm check-in tuyệt đẹp với thảm lúa vàng óng ả vắt ngang sườn núi vào mùa thu (tháng 9-10) và rực rỡ sắc trắng tinh khôi của mùa hoa lê vào đầu xuân (tháng 2-3). Khí hậu quanh năm mát mẻ như Sapa thu nhỏ.',
    tags: ['Nhiếp ảnh', 'Thiên nhiên', 'Hoa lê', 'Mùa lúa chín'],
    amenities: ['Homestay Tày', 'Cafe ngắm cảnh', 'Bãi đỗ xe'],
    social: {},
    reviews: []
  },
  {
    id: 306,
    name: 'Lễ hội Thành Tuyên',
    slug: 'le-hoi-thanh-tuyen',
    category: 'du-lich',
    subCategory: 'Lễ hội',
    rating: 5.0,
    totalReviews: 5420,
    image: 'https://images.unsplash.com/photo-1533512800412-1f3eb17b1836?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1533512800412-1f3eb17b1836?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1543781313-09403d6d091f?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#FF5733', '#C70039'],
    address: 'Quảng trường Nguyễn Tất Thành, TP. Tuyên Quang',
    phone: '',
    coordinates: { lat: 21.8205, lng: 105.2155 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'Tết Trung Thu (Tháng 8 Âm lịch)',
    isOpen: true,
    isFeatured: true,
    isNew: true,
    description: 'Lễ hội rước đèn Trung Thu lớn nhất Việt Nam. Hàng trăm mô hình đèn khổng lồ mô phỏng các con vật trong truyền thuyết và đời sống được người dân tự làm và rước khắp các ngọn phố, tạo nên một đêm hội ánh sáng rực rỡ và sôi động không thể bỏ lỡ.',
    tags: ['Trung Thu', 'Rước đèn', 'Đông đúc', 'Sự kiện năm'],
    amenities: ['Chợ đêm', 'Đường hoa', 'Gửi xe'],
    social: {},
    reviews: []
  },
  {
    id: 307,
    name: 'Lễ hội Động Tiên',
    slug: 'le-hoi-dong-tien',
    category: 'du-lich',
    subCategory: 'Lễ hội',
    rating: 4.8,
    totalReviews: 890,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#28B463', '#1D8348'],
    address: 'Huyện Hàm Yên, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 22.0620, lng: 105.0210 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'Mùng 9 tháng Giêng',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    description: 'Lễ hội Động Tiên và Chợ quê Hàm Yên là lễ hội đầu xuân truyền thống, thu hút du khách tham gia các trò chơi dân gian như chọi dê, kéo co, đánh đu và thưởng thức ẩm thực chợ quê đặc sắc như bánh nếp, thịt chua.',
    tags: ['Lễ hội xuân', 'Chợ quê', 'Trò chơi dân gian', 'Văn hóa'],
    amenities: ['Chợ ẩm thực', 'Bãi đỗ xe'],
    social: {},
    reviews: []
  },
  {
    id: 308,
    name: 'Lễ hội Nhảy lửa của người Pà Thẻn',
    slug: 'le-hoi-nhay-lua-pa-then',
    category: 'du-lich',
    subCategory: 'Lễ hội',
    rating: 4.9,
    totalReviews: 1200,
    image: 'https://images.unsplash.com/photo-1549468057-5ce754b5dfd6?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1549468057-5ce754b5dfd6?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#D35400', '#A04000'],
    address: 'Xã Hồng Quang, huyện Lâm Bình, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 22.3815, lng: 105.2890 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'Tháng 10 đến tháng Giêng',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    description: 'Nghi lễ tâm linh độc đáo và kỳ bí bậc nhất của người Pà Thẻn. Các chàng trai được "thần linh nhập" sẽ nhảy múa bằng chân trần trên đống than hồng rực mà không hề bị bỏng, thể hiện sức mạnh và cầu mong mùa màng bội thu.',
    tags: ['Tâm linh', 'Kỳ bí', 'Bản sắc', 'Văn hóa'],
    amenities: ['Lưu trú Homestay', 'Hướng dẫn viên'],
    social: {},
    reviews: []
  }
];
