// Tourism data for Tuyên Quang
// Each item needs all required fields to work with detail pages

export const TOURISM_PLACES = [
  {
    id: 302,
    name: 'Khu Di Tích Lịch Sử ATK Tân Trào',
    slug: 'atk-tan-trao',
    category: 'du-lich',
    subCategory: 'Di tích lịch sử',
    rating: 4.9,
    totalReviews: 2450,
    image: 'https://images.unsplash.com/photo-1542361345-89e58247f2d5?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1542361345-89e58247f2d5?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1601618332147-380145df0e59?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#7C9082', '#4A5B4D'],
    address: 'Xã Tân Trào, huyện Sơn Dương, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 21.68, lng: 105.32 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'T2-CN: 07:00 - 17:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    description: 'Thủ đô Khu Giải phóng - Căn cứ địa cách mạng hào hùng. Phiên bản 2026 đã kiện toàn Bảo tàng ATK Tân Trào hiện đại, kết hợp tham quan Lán Nà Nưa, Cây đa Tân Trào và Đình Hồng Thái với nhiều ứng dụng công nghệ thực tế ảo.',
    tags: ['Lịch sử', 'Văn hóa', 'Bảo tàng', 'Tâm linh'],
    amenities: ['Bãi đỗ xe rộng', 'Thuyết minh viên', 'Bảo tàng số', 'Khu mua sắm'],
    social: {},
    reviews: []
  },
  {
    id: 303,
    name: 'Khu Du Lịch Sinh Thái Na Hang - Lâm Bình',
    slug: 'na-hang-lam-binh',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    rating: 5.0,
    totalReviews: 3200,
    image: 'https://images.unsplash.com/photo-1506461883276-594c8cb257a1?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1506461883276-594c8cb257a1?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#2B4B6F', '#1A2F45'],
    address: 'Huyện Na Hang và Lâm Bình, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 22.35, lng: 105.39 },
    priceRange: '500.000đ - 2.500.000đ',
    priceText: '500.000đ - 2.500.000đ',
    openHours: 'T2-CN: 06:00 - 22:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    description: 'Được mệnh danh là "Hạ Long giữa đại ngàn". Khu du lịch nổi bật với các hoạt động mới như chèo kayak trên hồ thủy điện, trekking khám phá hang động hoang sơ, cắm trại qua đêm và chiêm ngưỡng danh thắng Cọc Vài Phạ hùng vĩ.',
    tags: ['Khám phá', 'Cảnh quan', 'Cắm trại', 'Chèo Kayak'],
    amenities: ['Tàu du lịch', 'Homestay', 'Cho thuê Kayak', 'Nhà hàng nổi'],
    social: {},
    reviews: []
  },
  {
    id: 304,
    name: 'Suối Khoáng Nóng Mỹ Lâm',
    slug: 'suoi-khoang-my-lam',
    category: 'du-lich',
    subCategory: 'Suối & Thác',
    rating: 4.7,
    totalReviews: 1540,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1621293954908-907159247fc8?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#8A9A5B', '#556B2F'],
    address: 'Phường Mỹ Lâm, TP. Tuyên Quang',
    phone: '',
    coordinates: { lat: 21.75, lng: 105.18 },
    priceRange: '150.000đ - 1.000.000đ',
    priceText: '150.000đ - 1.000.000đ',
    openHours: 'T2-CN: 08:00 - 21:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    description: 'Khu du lịch nghỉ dưỡng cao cấp với nguồn nước khoáng nóng tự nhiên dưới lòng đất (68 độ C), giàu khoáng chất cực kỳ tốt cho sức khỏe. Tại đây có các dịch vụ tắm bùn khoáng, tắm sục, spa trị liệu chuẩn quốc tế.',
    tags: ['Nghỉ dưỡng', 'Trị liệu', 'Gia đình', 'Spa'],
    amenities: ['Resort', 'Tắm bùn', 'Hồ bơi khoáng nóng', 'Nhà hàng'],
    social: {},
    reviews: []
  },
  {
    id: 305,
    name: 'Ruộng Bậc Thang Hồng Thái',
    slug: 'ruong-bac-thang-hong-thai',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    rating: 4.9,
    totalReviews: 890,
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80',
    images: [
        'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?auto=format&fit=crop&q=80'
    ],
    imageColors: ['#C5A059', '#8C6C3A'],
    address: 'Xã Hồng Thái, huyện Na Hang, tỉnh Tuyên Quang',
    phone: '',
    coordinates: { lat: 22.45, lng: 105.45 },
    priceRange: 'Miễn phí',
    priceText: 'Miễn phí',
    openHours: 'T2-CN: 06:00 - 18:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    description: 'Điểm check-in tuyệt đẹp với thảm lúa vàng óng ả vắt ngang sườn núi vào mùa thu (tháng 9-10) và rực rỡ sắc trắng tinh khôi của mùa hoa lê vào đầu xuân (tháng 2-3). Khí hậu quanh năm mát mẻ như Sapa thu nhỏ.',
    tags: ['Nhiếp ảnh', 'Thiên nhiên', 'Hoa lê', 'Mùa lúa chín'],
    amenities: ['Homestay Tày', 'Cafe ngắm cảnh', 'Bãi đỗ xe'],
    social: {},
    reviews: []
  }
];
