// js/tourism-data.js

export const TOURISM_PLACES = [
  // ============================================
  // TUYÊN QUANG ORIGINAL
  // ============================================
  {
    id: 101,
    name: 'Hồ sinh thái Na Hang',
    slug: 'ho-sinh-thai-na-hang',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: 'Được mệnh danh là "Hạ Long giữa núi rừng" với mặt nước rộng hơn 8.000 ha và núi đá vôi hùng vĩ.',
    fullDescription: 'Hồ sinh thái Na Hang (Hồ thủy điện Tuyên Quang) là một trong những điểm du lịch nổi tiếng nhất Tuyên Quang. Hồ có diện tích mặt nước rộng hơn 8.000 ha, được bao bọc bởi những dãy núi đá vôi trùng điệp. Nổi bật với Cọc Vài Phạ (cọc buộc trâu trời) và những thác nước hoang sơ. Du khách có thể thuê thuyền ngắm cảnh, tắm suối Khuổi Nhi và khám phá các bản làng người Tày, Dao.',
    address: 'Huyện Na Hang và Lâm Bình, Tuyên Quang',
    priceRange: '$$',
    priceText: 'Vé tham quan: 40.000đ/người. Thuê thuyền: 1-4 triệu.',
    rating: 4.8,
    totalReviews: 320,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#2A9D8F', '#1E7B6F'],
    openHours: '07:00 - 18:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Thiên nhiên', 'Check-in', 'Du thuyền'],
    amenities: ['Bãi đỗ xe', 'Thuyền du lịch', 'Ăn uống', 'Homestay'],
    coordinates: { lat: 22.3500, lng: 105.4000 },
    social: {
        facebook: '',
        zalo: '',
        instagram: ''
    },
    reviews: []
  },
  {
    id: 102,
    name: 'Khu du lịch sinh thái Lâm Bình',
    slug: 'khu-du-lich-sinh-thai-lam-binh',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: '"Hạ Long trên cạn" với Thung lũng Thượng Lâm tuyệt đẹp và 99 ngọn núi đá vôi.',
    fullDescription: 'Lâm Bình là huyện vùng cao có cảnh quan hoang sơ hùng vĩ, gắn liền với Thung lũng Thượng Lâm và 99 ngọn núi đá vôi. Nơi đây là điểm đến lý tưởng cho du lịch sinh thái và trải nghiệm văn hóa của các dân tộc Tày, Dao, Pà Thẻn. Du khách có thể ngủ homestay nhà sàn truyền thống, thưởng thức đặc sản thịt lợn đen, măng rừng và chèo thuyền mảng trên suối.',
    address: 'Huyện Lâm Bình, Tuyên Quang',
    priceRange: '$',
    priceText: 'Homestay ~150.000đ/đêm',
    rating: 4.7,
    totalReviews: 215,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#8AB060', '#4E732E'],
    openHours: 'Cả ngày',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['Văn hóa', 'Bản làng', 'Thiên nhiên'],
    amenities: ['Homestay', 'Đốt lửa trại', 'Giao lưu văn nghệ'],
    coordinates: { lat: 22.4500, lng: 105.3000 },
    social: {},
    reviews: []
  },
  {
    id: 103,
    name: 'Thác Khuổi Nhi',
    slug: 'thac-khuoi-nhi',
    category: 'du-lich',
    subCategory: 'Suối & Thác',
    description: 'Thác nước dài 3km nổi tiếng với trải nghiệm "massage cá suối" độc đáo giữa rừng già.',
    fullDescription: 'Nằm trong khu vực lòng hồ sinh thái Na Hang - Lâm Bình, Thác Khuổi Nhi là điểm dừng chân không thể bỏ qua. Thác có 5 tầng lớn nhỏ, rủ xuống như dải lụa trắng. Điều đặc biệt nhất ở đây là những đàn cá suối dạn dĩ. Chỉ cần ngâm chân xuống nước, hàng chục chú cá sẽ bơi đến rỉa tế bào chết, mang lại trải nghiệm massage tự nhiên vô cùng thú vị.',
    address: 'Xã Thượng Lâm, huyện Lâm Bình, Tuyên Quang',
    priceRange: '$',
    priceText: 'Đã bao gồm trong vé thuyền',
    rating: 4.9,
    totalReviews: 450,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#A8DADC', '#457B9D'],
    openHours: '08:00 - 17:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Thác nước', 'Massage cá', 'Trekking'],
    amenities: ['Điểm tắm', 'Áo phao', 'Quán nước nhỏ'],
    coordinates: { lat: 22.3800, lng: 105.3500 },
    social: {},
    reviews: []
  },
  {
    id: 104,
    name: 'Danh thắng Quốc gia Thác Bản Ba',
    slug: 'thac-ban-ba',
    category: 'du-lich',
    subCategory: 'Suối & Thác',
    description: 'Thác nước hùng vĩ gồm 3 tầng lớn đổ xuống từ độ cao hàng chục mét giữa rừng nguyên sinh.',
    fullDescription: 'Thác Bản Ba thuộc xã Trung Hà, huyện Chiêm Hóa. Thác gồm 3 tầng: Tát Củm (tầng 1) hùng vĩ nhất, Thác Cao (tầng 2) rẽ làm hai nhánh như dải lụa trắng, và Vực Linh (tầng 3) êm đềm tĩnh lặng. Đây là điểm đến lý tưởng cho những ai thích trekking nhẹ nhàng và đắm mình vào dòng nước mát lạnh.',
    address: 'Thôn Bản Ba, xã Trung Hà, huyện Chiêm Hóa, Tuyên Quang',
    priceRange: '$',
    priceText: 'Vé tham quan ~30.000đ',
    rating: 4.6,
    totalReviews: 180,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#2A9D8F', '#1D3557'],
    openHours: '07:00 - 17:30',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['Trekking', 'Thác nước', 'Sinh thái'],
    amenities: ['Bãi gửi xe', 'Nhà hàng', 'Homestay Tày'],
    coordinates: { lat: 22.3167, lng: 105.0167 },
    social: {},
    reviews: []
  },
  {
    id: 105,
    name: 'Suối khoáng nóng Mỹ Lâm',
    slug: 'suoi-khoang-my-lam',
    category: 'du-lich',
    subCategory: 'Khách sạn & Homestay',
    description: 'Nguồn nước khoáng thiên nhiên 67°C, tốt cho xương khớp và phục hồi sức khỏe.',
    fullDescription: 'Nằm cách trung tâm TP Tuyên Quang khoảng 13km, suối khoáng Mỹ Lâm nổi tiếng với nguồn nước khoáng chứa sunphua ngầm sâu 150m. Nước luôn ở nhiệt độ 67°C, rất tốt cho việc điều trị các bệnh về xương khớp, thần kinh, ngoài da. Tại đây có đầy đủ các dịch vụ tắm khoáng, tắm bùn, tắm lá thuốc người Dao.',
    address: 'Phường Mỹ Lâm, TP Tuyên Quang',
    priceRange: '$$',
    priceText: '80.000đ - 300.000đ/vé',
    rating: 4.5,
    totalReviews: 560,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#E9C46A', '#F4A261'],
    openHours: '07:00 - 19:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Nghỉ dưỡng', 'Spa', 'Tắm bùn'],
    amenities: ['Bể bơi khoáng', 'Phòng xông hơi', 'Khách sạn', 'Massage'],
    coordinates: { lat: 21.7800, lng: 105.1800 },
    social: {},
    reviews: []
  },
  {
    id: 106,
    name: 'Khu di tích lịch sử Tân Trào',
    slug: 'khu-di-tich-tan-trao',
    category: 'du-lich',
    subCategory: 'Di tích lịch sử',
    description: '"Thủ đô khu giải phóng", nơi ghi dấu những sự kiện trọng đại của cách mạng Việt Nam.',
    fullDescription: 'Tân Trào là một thung lũng nhỏ thuộc huyện Sơn Dương, từng là trung tâm của căn cứ địa Việt Bắc thời kỳ kháng chiến chống Pháp. Các điểm tham quan chính gồm có: Cây đa Tân Trào lịch sử, Lán Nà Nưa (nơi Bác Hồ từng sống và làm việc), Đình Tân Trào (nơi tổ chức Quốc dân Đại hội).',
    address: 'Xã Tân Trào, huyện Sơn Dương, Tuyên Quang',
    priceRange: '$',
    priceText: 'Vé 20.000đ/người',
    rating: 4.7,
    totalReviews: 890,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#2B9348', '#007F5F'],
    openHours: '07:30 - 17:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['Lịch sử', 'Cách mạng', 'Về nguồn'],
    amenities: ['Hướng dẫn viên', 'Xe điện', 'Bãi đỗ xe'],
    coordinates: { lat: 21.7000, lng: 105.4000 },
    social: {},
    reviews: []
  },
  {
    id: 107,
    name: 'Thành Nhà Mạc (Thành cổ Tuyên Quang)',
    slug: 'thanh-nha-mac',
    category: 'du-lich',
    subCategory: 'Di tích lịch sử',
    description: 'Bức tường thành cổ kính bằng đá ong nằm giữa lòng trung tâm thành phố.',
    fullDescription: 'Thành được nhà Mạc xây dựng từ thế kỷ 16 (1533-1548) để trấn giữ vùng biên ải. Thành có hình vuông, mỗi bề dài 275m, được xây bằng loại gạch đá ong đặc trưng chứa quặng sắt. Dù đã trải qua nhiều thăng trầm lịch sử và bị tàn phá một phần, các cổng thành cổ kính vẫn đứng vững giữa lòng thành phố hiện đại.',
    address: 'Tổ 8, phường Tân Quang, TP Tuyên Quang',
    priceRange: '$',
    priceText: 'Miễn phí',
    rating: 4.4,
    totalReviews: 125,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#9C6644', '#7F4F24'],
    openHours: 'Cả ngày',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['Lịch sử', 'Kiến trúc', 'City Tour'],
    amenities: ['Công viên', 'Ghế đá'],
    coordinates: { lat: 21.8200, lng: 105.2200 },
    social: {},
    reviews: []
  },
  
  // ============================================
  // HÀ GIANG DESTINATIONS (Merged into TQ)
  // ============================================
  {
    id: 108,
    name: 'Cao nguyên đá Đồng Văn',
    slug: 'cao-nguyen-da-dong-van',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: 'Công viên địa chất toàn cầu UNESCO với những ngọn núi đá tai mèo xám xịt trùng điệp.',
    fullDescription: 'Cao nguyên đá Đồng Văn trải rộng trên 4 huyện Quản Bạ, Yên Minh, Đồng Văn, Mèo Vạc ở độ cao 1.000 - 1.600m. Đây là vùng núi đá vôi mang nhiều dấu ấn lịch sử phát triển của vỏ Trái Đất. Không chỉ hùng vĩ về cảnh quan tự nhiên, đây còn là nơi bảo tồn nền văn hóa độc đáo của đồng bào dân tộc Mông với những nếp nhà trình tường, bờ rào đá đặc trưng.',
    address: 'Đồng Văn, Mèo Vạc, Quản Bạ, Yên Minh, Hà Giang (Tuyên Quang)',
    priceRange: '$',
    priceText: 'Phí lưu trú 30.000đ/người/đêm',
    rating: 4.9,
    totalReviews: 3500,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#6C757D', '#343A40'],
    openHours: '24/7',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['UNESCO', 'Phượt', 'Đá tai mèo'],
    amenities: ['Homestay', 'Cafe', 'Thuê xe máy', 'Viewpoint'],
    coordinates: { lat: 23.2800, lng: 105.3600 },
    social: {},
    reviews: []
  },
  {
    id: 109,
    name: 'Cột cờ Lũng Cú',
    slug: 'cot-co-lung-cu',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: 'Điểm cực Bắc thiêng liêng của Tổ quốc với lá cờ đỏ sao vàng rộng 54m2 tung bay trong gió.',
    fullDescription: 'Nằm trên đỉnh núi Rồng (Long Sơn) cao 1.470m so với mực nước biển, Cột cờ Lũng Cú là biểu tượng chủ quyền thiêng liêng ở cực Bắc Việt Nam. Lá cờ có diện tích 54m2 tượng trưng cho 54 dân tộc anh em. Vượt qua 389 bậc thang đá, bạn sẽ được chiêm ngưỡng toàn cảnh núi rừng biên giới ngoạn mục và bản Lô Lô Chải thanh bình bên dưới.',
    address: 'Xã Lũng Cú, huyện Đồng Văn',
    priceRange: '$',
    priceText: 'Vé 25.000đ + Xe điện 15.000đ',
    rating: 4.8,
    totalReviews: 2800,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#D62828', '#F77F00'],
    openHours: '07:00 - 17:30',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Check-in', 'Lịch sử', 'Leo núi'],
    amenities: ['Xe điện', 'Quán nước', 'Chỗ đỗ xe', 'Cửa hàng lưu niệm'],
    coordinates: { lat: 23.3600, lng: 105.3100 },
    social: {},
    reviews: []
  },
  {
    id: 110,
    name: 'Đèo Mã Pí Lèng',
    slug: 'deo-ma-pi-leng',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: 'Một trong "tứ đại đỉnh đèo" Việt Nam với những khúc cua hiểm trở và cảnh sắc ngoạn mục.',
    fullDescription: 'Đèo Mã Pí Lèng dài khoảng 20km, nối liền thị trấn Đồng Văn và Mèo Vạc. Tên đèo theo tiếng Mông nghĩa là "sống mũi con ngựa". Chạy xe trên cung đường này là một trải nghiệm nghẹt thở nhưng cực kỳ đáng giá. Đứng từ trên đèo nhìn xuống, bạn sẽ thấy dòng sông Nho Quế màu xanh ngọc bích chảy lững lờ dưới hẻm vực sâu thăm thẳm.',
    address: 'Quốc lộ 4C, Đồng Văn - Mèo Vạc',
    priceRange: '$',
    priceText: 'Miễn phí',
    rating: 5.0,
    totalReviews: 4200,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#003049', '#D62828'],
    openHours: '24/7',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Phượt', 'Mạo hiểm', 'Cảnh quan'],
    amenities: ['Điểm dừng chân', 'Cafe Panorama', 'Cho thuê trang phục'],
    coordinates: { lat: 23.2200, lng: 105.4200 },
    social: {},
    reviews: []
  },
  {
    id: 111,
    name: 'Sông Nho Quế & Hẻm Tu Sản',
    slug: 'song-nho-que-hem-tu-san',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: 'Đi thuyền trên dòng sông xanh ngọc bích qua hẻm vực sâu nhất Đông Nam Á.',
    fullDescription: 'Hẻm Tu Sản có chiều cao vách đá lên tới 800m, dài 1,7km và sâu gần 1km, là hẻm vực sâu nhất Đông Nam Á. Trải nghiệm tuyệt vời nhất là thuê thuyền máy hoặc tự chèo kayak trên sông Nho Quế, luồn lách qua hẻm vực khổng lồ và cảm nhận sự hùng vĩ tới choáng ngợp của thiên nhiên.',
    address: 'Bến Tà Làng hoặc Bến Xín Cái, Mèo Vạc',
    priceRange: '$$',
    priceText: 'Vé thuyền 120.000đ - 150.000đ/người',
    rating: 4.9,
    totalReviews: 3100,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#219EBC', '#023047'],
    openHours: '07:00 - 17:00',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Du thuyền', 'Chụp ảnh', 'Thiên nhiên'],
    amenities: ['Bến thuyền', 'Cho thuê kayak', 'Đưa đón xe ôm'],
    coordinates: { lat: 23.2300, lng: 105.4100 },
    social: {},
    reviews: []
  },
  {
    id: 112,
    name: 'Phố cổ Đồng Văn',
    slug: 'pho-co-dong-van',
    category: 'du-lich',
    subCategory: 'Di tích lịch sử',
    description: 'Khu phố cổ trăm năm tuổi nằm lọt thỏm giữa thung lũng đá, sôi động về đêm.',
    fullDescription: 'Hình thành từ đầu thế kỷ 20, phố cổ Đồng Văn mang đậm kiến trúc giao thoa của các dân tộc. Những ngôi nhà 2 tầng mái ngói âm dương, tường trình đất nện đã ngả màu thời gian. Cuối tuần, nơi đây trở nên nhộn nhịp với chợ phiên, các hàng quán bán thắng cố, bánh cuốn chả, mèn mén. Buổi tối, du khách thường tản bộ, uống cà phê và xem các màn trình diễn khèn Mông.',
    address: 'Thị trấn Đồng Văn',
    priceRange: '$',
    priceText: 'Vào tự do',
    rating: 4.6,
    totalReviews: 1850,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#E9C46A', '#264653'],
    openHours: 'Cả ngày (nhộn nhịp nhất buổi tối)',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['Văn hóa', 'Ẩm thực', 'Chợ phiên'],
    amenities: ['Cafe', 'Nhà hàng', 'Homestay', 'Chợ'],
    coordinates: { lat: 23.2700, lng: 105.3600 },
    social: {},
    reviews: []
  },
  {
    id: 113,
    name: 'Dinh thự Vua Mèo (Nhà Vương)',
    slug: 'dinh-thu-vua-meo',
    category: 'du-lich',
    subCategory: 'Di tích lịch sử',
    description: 'Dinh thự bằng đá xanh và gỗ thông sa mu của vua Mèo Vương Chính Đức.',
    fullDescription: 'Nằm tại thung lũng Sà Phìn, Dinh thự Vua Mèo được xây dựng từ năm 1898 với kiến trúc vô cùng độc đáo, kết hợp giữa phong cách đời Thanh (Trung Quốc), nghệ thuật chạm khắc của người Mông và một số chi tiết kiểu Pháp. Khu dinh thự có 64 phòng, được bao quanh bởi những hàng cây sa mu cổ thụ, mang màu sắc huyền bí và câu chuyện lịch sử thú vị.',
    address: 'Xã Sà Phìn, huyện Đồng Văn',
    priceRange: '$',
    priceText: 'Vé 20.000đ/người',
    rating: 4.5,
    totalReviews: 1420,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#A98467', '#6C584C'],
    openHours: '07:30 - 17:00',
    isOpen: true,
    isFeatured: false,
    isNew: false,
    tags: ['Lịch sử', 'Kiến trúc', 'Văn hóa'],
    amenities: ['Hướng dẫn viên', 'Cửa hàng lưu niệm', 'Bãi gửi xe'],
    coordinates: { lat: 23.2200, lng: 105.3200 },
    social: {},
    reviews: []
  },
  {
    id: 114,
    name: 'Ruộng bậc thang Hoàng Su Phì',
    slug: 'ruong-bac-thang-hoang-su-phi',
    category: 'du-lich',
    subCategory: 'Danh thắng',
    description: 'Những nấc thang lên thiên đường tuyệt đẹp vào mùa lúa chín.',
    fullDescription: 'Ruộng bậc thang Hoàng Su Phì là Di tích danh thắng Quốc gia, được tạo nên từ hàng trăm năm lao động cần mẫn của đồng bào La Chí, Dao, Nùng. Ruộng trải dài qua các xã Bản Luốc, Bản Phùng, Nậm Ty... Đẹp nhất là vào mùa nước đổ (tháng 4-6) khi ruộng như những tấm gương soi bầu trời, và mùa lúa chín (tháng 9-10) khi cả sườn núi nhuộm màu vàng óng ả.',
    address: 'Huyện Hoàng Su Phì',
    priceRange: '$',
    priceText: 'Miễn phí',
    rating: 4.9,
    totalReviews: 2100,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#E9C46A', '#2A9D8F'],
    openHours: '24/7',
    isOpen: true,
    isFeatured: true,
    isNew: false,
    tags: ['Thiên nhiên', 'Nhiếp ảnh', 'Lúa chín'],
    amenities: ['Homestay', 'Cafe view núi', 'Bãi đỗ xe'],
    coordinates: { lat: 22.7400, lng: 104.6300 },
    social: {},
    reviews: []
  },
  {
    id: 115,
    name: 'Bản Du Già',
    slug: 'ban-du-gia',
    category: 'du-lich',
    subCategory: 'Khách sạn & Homestay',
    description: 'Bản làng hoang sơ, yên bình với những con thác tuyệt đẹp và văn hóa bản địa.',
    fullDescription: 'Du Già là một xã thuộc huyện Yên Minh, được ví như chốn tiên cảnh bị lãng quên. Nơi đây có phong cảnh núi rừng nguyên sơ, những nương ngô xanh mướt và thác nước Thâm Luông trong vắt. Du Già đặc biệt thu hút du khách quốc tế nhờ văn hóa homestay cực kỳ phát triển, những bữa ăn gia đình (family dinner) ấm cúng và sự hiếu khách của đồng bào Tày, Mông.',
    address: 'Xã Du Già, huyện Yên Minh',
    priceRange: '$',
    priceText: 'Homestay 100.000đ - 300.000đ/đêm',
    rating: 4.8,
    totalReviews: 950,
    images: ['https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800'],
    imageColors: ['#40916C', '#1B4332'],
    openHours: '24/7',
    isOpen: true,
    isFeatured: false,
    isNew: true,
    tags: ['Trekking', 'Tắm thác', 'Homestay'],
    amenities: ['Homestay', 'Quán ăn', 'Thuê xe máy', 'Tắm suối'],
    coordinates: { lat: 23.1000, lng: 105.5500 },
    social: {},
    reviews: []
  }
];

